slam_node:
  world_frame_id: map
  base_frame_id: base_footprint
  lidar_sensor_frame: rslidar

  use_semantic_features: False
  use_lidar_features: True
  use_vertical_planes: False
  use_ground_plane: False
  use_imu: False
  use_gyroscope: False
  use_gps: False
  use_gps_altitude: False
  use_gps_heading: False

  publish_level: 2 # 0 - do not publish any map
                   # 1 - publish only the 3D map
                   # 2 - publish all the maps

  robot_dimensions:
    x: 0.42 # meters
    y: 0.32 # meters
    z: 0.37 # meters

  multilayer_mapping:
    # Datum
    datum:
      latitude: 45.706199
      longitude: 7.2495435
      altitude: 668.63

    # Topological map definitions
    topological_map:
      autogen_topological_map: True
      folder: "/home/sousarbarb/.ros/vineslam/"
      dimensions:
        x: 100.0 # meters
        y: 100.0 # meters
        square_size: 20.0 # meters

    # Grid map definitions
    grid_map:
      origin:
        z: 0.0 # meters
      height: 30.0 # meters
      resolution: 0.25 # meters

  pf:
    n_particles: 300

    # Particles innovation
    sigma_xx: 0.3 # meters
    sigma_yy: 0.3 # meters
    sigma_zz: 0.2 # meters
    sigma_RR: 0.1 # radians
    sigma_PP: 0.1 # radians
    sigma_YY: 0.2 # radians
